apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vm-services
  namespace: default
spec:
  host: "*.vm.local"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50