apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: orders-vm
  namespace: default
spec:
  hosts:
  - orders.vm.mesh               
  endpoints:
  - address: 10.10.1.5            
    ports: { http: 8080 }
  - address: 10.10.1.6            
    ports: { http: 8080 }
  location: MESH_EXTERNAL
  resolution: STATIC
  ports:
  - number: 8080
    name: http
    protocol: HTTP